import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const labels={clients:'Clientes',sites:'Obras',pumps:'Bombas',helpers:'Ajudantes'};
const states={draft:'Rascunho',submitted:'Submetido',approved:'Aprovado',returned:'Devolvido'};
const blank={client_id:'',site_id:'',pump_id:'',helper_id:'',start:'',end:'',pause_minutes:0,concrete_m3:'',line_m:'',origin:'',destination:'',notes:''};
function App(){
 const [token,setToken]=useState(sessionStorage.getItem('token')||''),[user,setUser]=useState(null),[page,setPage]=useState('entries'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[rows,setRows]=useState([]),[catalog,setCatalog]=useState({clients:[],sites:[],pumps:[],helpers:[]}),[form,setForm]=useState({...blank}),[editing,setEditing]=useState(null),[report,setReport]=useState(null),[users,setUsers]=useState([]),[history,setHistory]=useState(null),[filters,setFilters]=useState({date_from:'',date_to:'',operator_id:'',client_id:'',site_id:'',pump_id:''});
 async function api(path,options={}){
  const response=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});
  if(!response.ok){if(response.status>=500)throw Error('O servidor está indisponível. Tente novamente após verificar a API.');if(response.status===429)throw Error('Muitas tentativas. Aguarde um momento antes de tentar novamente.');let data=await response.json().catch(()=>({})); if(response.status===401&&token){sessionStorage.removeItem('token');setToken('');setUser(null);} throw Error(typeof data.detail==='string'?data.detail:'Verifique os campos e horários.');}
  return response;
 }
 async function action(fn){setError('');setBusy(true);try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const query=()=>{let p=new URLSearchParams();for(let [k,v] of Object.entries(filters)){if(!v)continue;if(k.startsWith('date_')){let d=new Date(v+'T00:00:00');if(k==='date_to')d.setDate(d.getDate()+1);v=d.toISOString();}p.set(k,v);}return '?'+p.toString();};
 async function load(){const me=await (await api('/auth/me')).json();setUser(me);const lists=await Promise.all(Object.keys(labels).map(async k=>[k,await(await api('/catalog/'+k+(me.role==='admin'?'?include_inactive=true':''))).json()]));setCatalog(Object.fromEntries(lists));setRows(await(await api('/entries')).json());if(me.role==='admin')setUsers(await(await api('/users')).json());}
 useEffect(()=>{if(token)action(load);},[token]);
 function select(name,title,items,optional=false){return <label>{title}<select value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value,...(name==='client_id'?{site_id:''}:{})})} required={!optional}><option value="">{optional?'Sem ajudante':'Selecionar'}</option>{items.filter(x=>x.active||x.id===Number(form[name])).map(x=><option key={x.id} value={x.id}>{x.name}{!x.active?' (inativo)':''}</option>)}</select></label>;}
 function input(name,title,type='text'){return <label>{title}<input type={type} required={!['notes','pause_minutes'].includes(name)} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>;}
 function localDate(value){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
 function edit(row){setEditing(row);setForm({...row,start:localDate(row.start),end:localDate(row.end),helper_id:row.helper_id||''});setPage('new');}
 async function save(event){event.preventDefault();await action(async()=>{let data={...form,client_id:Number(form.client_id),site_id:Number(form.site_id),pump_id:Number(form.pump_id),helper_id:form.helper_id?Number(form.helper_id):null,pause_minutes:Number(form.pause_minutes),start:new Date(form.start).toISOString(),end:new Date(form.end).toISOString()};await api('/entries'+(editing?'/'+editing.id:''),{method:editing?'PUT':'POST',body:JSON.stringify(data)});setEditing(null);setForm({...blank});await load();setPage('entries');});}
 async function change(row,status){await action(async()=>{if(status==='submit')await api(`/entries/${row.id}/submit?revision=${row.revision}`,{method:'POST'});else{const note=status==='returned'?prompt('Motivo da devolução:'):'';if(note===null)return;await api(`/entries/${row.id}/review`,{method:'POST',body:JSON.stringify({status,note,revision:row.revision})});}await load();});}
 if(!user)return <main className="login"><div className="brand">B / APONTAMENTOS</div><h1>Serviços de bombagem</h1><p>Registe o trabalho da equipa em cada obra.</p><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);action(async()=>{const r=await(await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(data))})).json();sessionStorage.setItem('token',r.access_token);setToken(r.access_token);setUser(r.user);});}}><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Senha<input name="password" type="password" required autoComplete="current-password"/></label><button disabled={busy}>Entrar</button></form>{error&&<p role="alert" className="error">{error}</p>}</main>;
 const admin=user.role==='admin';
 function table(data){return data.length?<div className="cards">{data.map(r=><article key={r.id}><div className="row"><strong>{r.site}</strong><span className={'badge '+r.status}>{states[r.status]}</span></div><p>{r.client} · {new Date(r.start).toLocaleDateString('pt-PT')}</p><p>{r.operator} · {r.pump}{r.helper?' · '+r.helper:''}</p><div className="metrics"><b>{r.hours} h</b><b>{r.concrete_m3} m³</b><b>{r.line_m} m de linha</b></div><p>{r.origin} → {r.destination}</p><small>{new Date(r.start).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})} – {new Date(r.end).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})} · Pausa: {r.pause_minutes} min</small>{r.notes&&<p>{r.notes}</p>}{r.review_note&&<p className="review">Revisão: {r.review_note}</p>}<div className="actions">{r.status!=='approved'&&(admin||['draft','returned'].includes(r.status))&&<button className="secondary" disabled={busy} onClick={()=>edit(r)}>Editar</button>}{['draft','returned'].includes(r.status)&&<button disabled={busy} onClick={()=>change(r,'submit')}>Submeter</button>}{admin&&r.status==='submitted'&&<><button disabled={busy} onClick={()=>change(r,'approved')}>Aprovar</button><button className="secondary" disabled={busy} onClick={()=>change(r,'returned')}>Devolver</button></>}{admin&&<button className="secondary" onClick={()=>action(async()=>setHistory(await(await api(`/entries/${r.id}/history`)).json()))}>Histórico</button>}</div></article>)}</div>:<div className="empty">Ainda não existem apontamentos para esta seleção.</div>;}
 return <><header><div className="brand">B / APONTAMENTOS</div><div>{user.name}<button className="secondary" onClick={()=>{sessionStorage.removeItem('token');setToken('');setUser(null);}}>Sair</button></div></header><nav>{[['entries','Apontamentos'],['new','Novo serviço'],...(admin?[['catalog','Cadastros'],['users','Utilizadores'],['reports','Relatórios']]:[])].map(([p,l])=><button className={page===p?'selected':'secondary'} key={p} onClick={()=>{setPage(p);if(p==='new'){setEditing(null);setForm({...blank});}}}>{l}</button>)}</nav><main>{error&&<p className="error" role="alert">{error}</p>}{page==='entries'&&<><div className="row"><h1>{admin?'Apontamentos da equipa':'Os meus apontamentos'}</h1><button disabled={busy} onClick={()=>action(load)}>Atualizar</button></div>{table(rows)}</>}
 {page==='new'&&<><h1>{editing?'Editar serviço':'Novo serviço'}</h1><p>Um apontamento por serviço. Pode registar várias obras no mesmo dia.</p><form onSubmit={save} className="panel"><div className="grid">{select('client_id','Cliente',catalog.clients)}{select('site_id','Obra',catalog.sites.filter(s=>s.client_id===Number(form.client_id)))}{select('pump_id','Bomba',catalog.pumps)}{select('helper_id','Ajudante',catalog.helpers,true)}{input('start','Início do trabalho na obra','datetime-local')}{input('end','Fim do trabalho na obra','datetime-local')}{input('pause_minutes','Pausa (minutos)','number')}{input('concrete_m3','Betão bombeado (m³)','number')}{input('line_m','Linha montada (metros)','number')}{input('origin','Origem da bomba/equipa')}{input('destination','Destino da bomba/equipa')}</div><label>Observações<textarea maxLength={5000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button disabled={busy}>Guardar rascunho</button></form></>}
 {page==='catalog'&&admin&&<><h1>Cadastros</h1><div className="grid">{Object.entries(labels).map(([kind,title])=><section className="panel" key={kind}><h2>{title}</h2><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,data=Object.fromEntries(new FormData(f));if(kind==='sites')data.client_id=Number(data.client_id);action(async()=>{await api('/catalog/'+kind,{method:'POST',body:JSON.stringify(data)});f.reset();await load();});}}><label>Nome<input name="name" required maxLength={200}/></label>{kind==='sites'&&<><label>Cliente<select name="client_id" required><option value="">Selecionar</option>{catalog.clients.filter(c=>c.active).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Morada<input name="address" maxLength={500}/></label></>}<button disabled={busy}>Adicionar</button></form><ul>{catalog[kind].map(c=><li key={c.id}>{c.name} {!c.active&&'(inativo)'}<button className="secondary" disabled={busy} onClick={()=>action(async()=>{await api(`/catalog/${kind}/${c.id}`,{method:'PUT',body:JSON.stringify({...c,active:!c.active})});await load();})}>{c.active?'Desativar':'Ativar'}</button><button className="secondary" disabled={busy} onClick={()=>{const name=prompt('Nome:',c.name);if(name)action(async()=>{await api(`/catalog/${kind}/${c.id}`,{method:'PUT',body:JSON.stringify({...c,name})});await load();});}}>Editar nome</button></li>)}</ul></section>)}</div></>}
 {page==='users'&&admin&&<><h1>Utilizadores</h1><form className="panel" onSubmit={e=>{e.preventDefault();let f=e.currentTarget;action(async()=>{await api('/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});f.reset();await load();});}}><div className="grid"><label>Nome<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Senha inicial<input name="password" type="password" required minLength={12}/></label><label>Perfil<select name="role"><option value="bombista">Bombista</option><option value="admin">Administrador</option></select></label></div><button disabled={busy}>Criar utilizador</button></form><ul>{users.map(u=><li key={u.id}>{u.name} · {u.email} · {u.role} {!u.active&&'· Inativo'}{u.id!==user.id&&<button className="secondary" onClick={()=>action(async()=>{await api(`/users/${u.id}/active?active=${!u.active}`,{method:'PATCH'});await load();})}>{u.active?'Desativar':'Ativar'}</button>}</li>)}</ul></>}
 {page==='reports'&&admin&&<><h1>Relatórios</h1><p>Totais dos serviços aprovados. Datas e horários apresentados no fuso do dispositivo.</p><form className="panel" onSubmit={e=>{e.preventDefault();action(async()=>setReport(await(await api('/reports'+query())).json()));}}><div className="grid">{['date_from','date_to'].map((k,i)=><label key={k}>{i?'Até':'Desde'}<input type="date" value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}/></label>)}{[['operator_id','Bombista',users],['client_id','Cliente',catalog.clients],['site_id','Obra',catalog.sites],['pump_id','Bomba',catalog.pumps]].map(([k,l,list])=><label key={k}>{l}<select value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}><option value="">Todos</option>{list.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>)}</div><div className="actions"><button disabled={busy}>Consultar</button><button disabled={busy} type="button" className="secondary" onClick={()=>action(async()=>{const blob=await(await api('/reports.csv'+query())).blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='apontamentos.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>Exportar CSV / Excel</button></div></form>{report&&<><div className="totals">{Object.entries(report.totals).map(([k,v])=><article key={k}><small>{{services:'Serviços',hours:'Horas',concrete_m3:'Betão (m³)',line_m:'Linha (m)'}[k]}</small><strong>{v}</strong></article>)}</div>{table(report.rows)}</>}</>}
 {history&&<section className="panel"><div className="row"><h2>Histórico de alterações</h2><button onClick={()=>setHistory(null)}>Fechar</button></div>{history.map((h,i)=><p key={i}><strong>{h.actor}</strong> · {new Date(h.at).toLocaleString('pt-PT')}<br/>{h.action}</p>)}</section>}
 </main><footer>Apontamentos de bombagem · V1</footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
